import React, { useState } from "react";
import { Inbox, CheckCircle2 } from "lucide-react";
import { AuditItem } from "../types";
import { auditService } from "../services/auditService";

interface ComplaintQueueTabProps {
  pendingComplaints: AuditItem[];
  registeredComplaints: AuditItem[];
  syncActiveItem: (item: AuditItem) => void;
  setActiveTab: (tab: any) => void;
  loadHistoricalAudits: () => Promise<void>;
  setAppStatus: (status: string) => void;
  setInvestigatorSubView?: (subView: "report" | "patient" | "locker" | "ai") => void;
}

export const ComplaintQueueTab: React.FC<ComplaintQueueTabProps> = ({
  pendingComplaints,
  registeredComplaints,
  syncActiveItem,
  setActiveTab,
  loadHistoricalAudits,
  setAppStatus,
  setInvestigatorSubView,
}) => {
  // Safe inline confirmation state to bypass sandboxed iframe browser confirm dialogs
  const [confirmingAction, setConfirmingAction] = useState<{
    itemId: string;
    status: "REGISTERED" | "DISMISSED";
  } | null>(null);

  const handleUpdateStatus = async (itemId: string, status: "REGISTERED" | "DISMISSED") => {
    try {
      const payload = await auditService.updateAuditStatus(itemId, status);
      if (payload.success) {
        setAppStatus(`Board Complaint Queue: Case status updated to [${status}]`);
        await loadHistoricalAudits();
      } else {
        throw new Error((payload as any).error || "Update denied.");
      }
    } catch (e: any) {
      setAppStatus(`Failed saving complaint state: ${e.message}`);
    }
  };

  return (
    <main className="flex-1 overflow-y-auto p-5 space-y-5 bg-[#090D14]">
      {/* Queue Header summary */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between bg-[#121620]/90 border border-[#21262D] p-5 rounded-2xl select-none shadow-md gap-4">
        <div className="space-y-1">
          <h2 className="text-sm font-bold text-white flex items-center gap-2 uppercase tracking-wider font-mono">
            <Inbox className="w-4 h-4 text-red-400" /> Complaint Review Queue Workspace
          </h2>
          <p className="text-[10px] text-[#8B949E] font-mono leading-relaxed">
            Review recommendations generated by low compliance par counts. State licensing authorities require defensive proof trails before filing.
          </p>
        </div>

        <div className="flex gap-5 text-xs font-mono">
          <div className="text-right">
            <span className="text-gray-500 block text-[8px] uppercase font-bold tracking-widest">Unreviewed & Saved</span>
            <span className="font-extrabold text-red-400 text-sm">{pendingComplaints.length} cases</span>
          </div>
          <div className="text-right">
            <span className="text-gray-500 block text-[8px] uppercase font-bold tracking-widest">Registered Filings</span>
            <span className="font-extrabold text-emerald-400 text-sm">{registeredComplaints.length} claims</span>
          </div>
        </div>
      </div>

      {/* Split pending vs registered list */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 font-mono text-xs select-text">
        {/* Left col: PENDING DRIVER */}
        <div className="space-y-4">
          <div className="flex items-center justify-between border-b border-[#21262D] pb-2">
            <span className="text-[9px] font-bold text-amber-400 uppercase tracking-widest flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-amber-500 animate-pulse"></span>
              Queue Waiting Manual Approval & Saved Reviews ({pendingComplaints.length})
            </span>
          </div>

          {pendingComplaints.length === 0 ? (
            <div className="p-8 rounded-2xl bg-[#121620]/30 border border-[#21262D] text-center text-gray-500 font-mono text-[10px]">
              No unreviewed high-risk cases. Create or select high-risk files.
            </div>
          ) : (
            pendingComplaints.map((item) => (
              <div
                key={item.id}
                className="relative overflow-hidden bg-[#121620] border border-[#21262D] rounded-2xl p-4.5 pl-6 space-y-4 hover:border-amber-500/20 transition-all shadow hover:shadow-lg hover:shadow-amber-500/2"
              >
                {/* Dynamic Score Left Bar */}
                <div
                  className={`absolute left-0 top-0 bottom-0 w-1.5 ${
                    item.complianceScore > 70 ? "bg-emerald-500" : item.complianceScore >= 50 ? "bg-amber-500" : "bg-red-500"
                  }`}
                />
                <div className="flex items-start justify-between gap-1.5">
                  <div className="space-y-0.5 font-sans">
                    <h4 className="font-bold text-white text-xs">{item.doctorName}</h4>
                    <span className="text-[10px] text-gray-400 block font-mono">
                      {item.doctorSpecialization} • {item.hospitalName}
                    </span>
                  </div>
                  <span className="px-2 py-0.5 rounded text-[9px] bg-red-950/40 border border-red-500/20 text-red-400 font-bold">
                    Rating {item.complianceScore}
                  </span>
                </div>

                <div className="space-y-1.5 text-[11px] text-gray-300 bg-[#090D14] p-3 rounded-xl border border-[#21262D]">
                  <span className="text-[#D29922] block font-bold text-[8px] uppercase tracking-wider">
                    Infraction Evidence Summary:
                  </span>
                  <p className="italic leading-relaxed">
                    &ldquo;{item.complaint?.evidenceSummary}&rdquo;
                  </p>
                </div>

                <div className="flex items-center justify-between pt-1 border-t border-[#21262D]">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    <span className="text-[8.5px] uppercase bg-amber-950/40 text-[#D29922] border border-amber-500/20 px-1.5 py-0.5 rounded font-bold">
                      {item.complaint?.severityLevel}
                    </span>
                    {item.complaint?.status === "SAVED FOR REVIEW" && (
                      <span className="text-[8.5px] uppercase bg-blue-950/40 text-blue-400 border border-blue-500/20 px-1.5 py-0.5 rounded font-bold flex items-center gap-1">
                        <span>Saved for Review ⏳</span>
                      </span>
                    )}
                  </div>

                  <div className="flex gap-2 flex-wrap items-center">
                    {confirmingAction?.itemId === item.id ? (
                      <div className="flex items-center gap-2 bg-[#1b1f27] border border-[#30363D] p-1.5 rounded-lg text-[9px] font-mono animate-fade-in">
                        <span className="text-gray-300 font-bold">Confirm {confirmingAction.status === "REGISTERED" ? "Registering" : "Dismissing"}?</span>
                        <button
                          onClick={async () => {
                            await handleUpdateStatus(confirmingAction.itemId, confirmingAction.status);
                            setConfirmingAction(null);
                          }}
                          className={`px-2 py-1 rounded font-bold uppercase cursor-pointer text-white transition-all ${
                            confirmingAction.status === "REGISTERED"
                              ? "bg-red-600 hover:bg-red-500"
                              : "bg-gray-600 hover:bg-gray-500"
                          }`}
                        >
                          Yes, {confirmingAction.status === "REGISTERED" ? "Register" : "Dismiss"}
                        </button>
                        <button
                          onClick={() => setConfirmingAction(null)}
                          className="bg-[#21262D] hover:bg-[#30363D] text-gray-300 px-2 py-1 rounded font-bold uppercase cursor-pointer transition-all"
                        >
                          Cancel
                        </button>
                      </div>
                    ) : (
                      <>
                        <button
                          onClick={() => {
                            syncActiveItem(item);
                            if (setInvestigatorSubView) {
                              setInvestigatorSubView("report");
                            }
                            setActiveTab("investigator");
                          }}
                          className="bg-[#1c212e] hover:bg-[#252b3a] text-blue-400 px-3 py-1.5 rounded-lg border border-[#21262D] text-[9px] font-bold uppercase tracking-wider transition-all cursor-pointer"
                          title="Recheck findings and view the full audit report details"
                        >
                          🔎 Recheck Details
                        </button>

                        <button
                          onClick={() => setConfirmingAction({ itemId: item.id, status: "DISMISSED" })}
                          className="bg-gray-850 hover:bg-gray-850 text-gray-300 px-3 py-1.5 rounded-lg border border-[#21262D] text-[9px] font-bold uppercase tracking-wider transition-all cursor-pointer"
                          title="Dismiss this case"
                        >
                          Dismiss
                        </button>

                        <button
                          onClick={() => setConfirmingAction({ itemId: item.id, status: "REGISTERED" })}
                          className="bg-red-500/10 hover:bg-red-500/20 text-red-400 px-3 py-1.5 rounded-lg border border-red-500/20 text-[9px] font-bold uppercase tracking-wider transition-all cursor-pointer"
                          title="Register official complaint"
                        >
                          Register
                        </button>
                      </>
                    )}
                  </div>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Right col: ARCHIVED SYSTEM COMPLAINTS */}
        <div className="space-y-4">
          <div className="flex items-center justify-between border-b border-[#21262D] pb-2">
            <span className="text-[9px] font-bold text-emerald-400 uppercase tracking-widest flex items-center gap-2 font-mono">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              REGISTERED FILINGS LOGS ({registeredComplaints.length})
            </span>
          </div>

          {registeredComplaints.length === 0 ? (
            <div className="p-8 rounded-2xl bg-[#121620]/30 border border-[#21262D] text-center text-gray-500 font-mono text-[10px]">
              No corporate clinical registered complaints in active session database. Approve recommendations to file claims.
            </div>
          ) : (
            registeredComplaints.map((item) => (
              <div
                key={item.id}
                className="relative overflow-hidden bg-[#121620] border border-emerald-500/15 rounded-2xl p-4.5 pl-6 space-y-4 shadow hover:shadow-lg transition-all"
              >
                {/* Dynamic Score Left Bar */}
                <div
                  className={`absolute left-0 top-0 bottom-0 w-1.5 ${
                    item.complianceScore > 70 ? "bg-emerald-500" : item.complianceScore >= 50 ? "bg-amber-500" : "bg-red-500"
                  }`}
                />
                <div className="flex items-start justify-between gap-1.5 font-sans">
                  <div className="space-y-0.5">
                    <h4 className="font-bold text-white text-xs">{item.doctorName}</h4>
                    <span className="text-[10px] text-gray-400 block font-mono">
                      {item.doctorSpecialization} • {item.hospitalName}
                    </span>
                  </div>
                  <span className="px-2.5 py-0.5 rounded text-[9px] bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-bold uppercase tracking-wider font-mono">
                    REGISTERED FILED
                  </span>
                </div>

                <div className="text-[11px] text-gray-300 bg-[#090D14] p-3 rounded-xl border border-emerald-500/10 font-sans">
                  <p className="leading-relaxed font-sans">
                    Patient safety case filed to licensing boards on {new Date(item.timestamp).toLocaleDateString()}. Claim ref
                    identifier prefix logged as: <span className="text-blue-400 font-bold font-mono">REG_CO_#{item.id}</span>
                  </p>
                </div>

                <div className="flex justify-between items-center text-[9px] uppercase font-bold text-gray-500">
                  <span>Severity: {item.complaint?.severityLevel.split(":")[0]}</span>
                  <span className="text-emerald-400 flex items-center gap-1 font-mono">
                    <span className="h-1.5 w-1.5 rounded-full bg-emerald-500"></span> Pending board audit
                  </span>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </main>
  );
};
